#ifndef INC_WAVETABLES_H_
#define INC_WAVETABLES_H_

#include <stdint.h>

// GENERATED by tools/gen_wavetable.py - do not edit. `just wavetable`.
//
// The SHAPE_LFO morphing wavetable: WT_SLICES shapes of WT_LEN samples, read
// with a bilinear lookup over phase and shape (wavetable.c).
//
// Every slice is built from an odd monotone rise curve, which is what makes
// three things true of every slice AND of every blend between neighbouring
// slices - the runtime interpolates, so a knob between two entries is the
// normal case:
//
//   * it reaches the full swing, -32767 at phase 0 and +32767 at phase 0.5;
//   * it has no DC offset, by half-wave antisymmetry;
//   * it stays inside the range.
//
// The shape axis is a loop, because SHP wraps at both the parameter and the
// lookup:
//
//   shape -1.000 ...... +0.000 ..... +0.375 ... +0.625 ... +1.000 (= -1.000)
//   square          SINE       TRIANGLE    pointy       square
//
// SINE is at shape 0, a channel's default, and is exact. So is TRIANGLE. See
// the generator for why saw, stepped and pulse shapes are deliberately absent.

#define WT_LEN 256
#define WT_SLICES 64

// Where the named shapes are, for tests and for anyone reading a value back.
#define WT_SLICE_SQUARE 0
#define WT_SLICE_SINE 32
#define WT_SLICE_TRIANGLE 44
#define WT_SLICE_POINTY 52

// Declared, not defined: the table lives in wavetables.c so that including this
// from a second translation unit links. It used to be defined here, which was
// invisible while exactly one file included it and a multiple-definition error
// the moment a test did.
extern const int16_t shape_table[WT_SLICES][WT_LEN];

#endif /* INC_WAVETABLES_H_ */
