// Generated by tools/gen_panel_spec.py - do not edit.
// Panel geometry in mm, origin at the board's top-left corner.
// Regenerate with `just panel`.
#ifndef BMCV_PANEL_LAYOUT_H_
#define BMCV_PANEL_LAYOUT_H_

#include <stdint.h>

typedef struct { float x, y; } PanelPoint;

#define PANEL_BOARD_W_MM 80.0f
#define PANEL_BOARD_H_MM 108.0f
#define PANEL_HP 16

static const PanelPoint panel_button_pos[24] =
{
  {25.500f, 56.000f}, //  0 U6
  {7.500f, 38.000f}, //  1 U1
  {25.500f, 38.000f}, //  2 U2
  {54.500f, 38.000f}, //  3 U3
  {7.500f, 56.000f}, //  4 U5
  {72.500f, 38.000f}, //  5 U4
  {72.500f, 56.000f}, //  6 U7
  {54.500f, 56.000f}, //  7 U8
  {22.750f, 92.500f}, //  8 SW2
  {17.000f, 103.500f}, //  9 SW8
  {11.250f, 92.500f}, // 10 SW1
  {5.500f, 103.500f}, // 11 SW7
  {34.250f, 92.500f}, // 12 SW3
  {28.500f, 103.500f}, // 13 SW9
  {40.000f, 103.500f}, // 14 SW10
  {45.750f, 92.500f}, // 15 SW4
  {57.250f, 92.500f}, // 16 SW5
  {68.750f, 92.500f}, // 17 SW6
  {51.500f, 103.500f}, // 18 SW11
  {63.000f, 103.500f}, // 19 SW12
  {74.500f, 103.500f}, // 20 SW13
  {40.000f, 38.000f}, // 21 SW14
  {40.000f, 52.000f}, // 22 SW15
  {40.000f, 66.000f}, // 23 SW16
};

static const PanelPoint panel_led_pos[21] =
{
  {54.500f, 56.000f}, //  0 U16 @ U8
  {72.500f, 56.000f}, //  1 U15 @ U7
  {72.500f, 38.000f}, //  2 U12 @ U4
  {54.500f, 38.000f}, //  3 U11 @ U3
  {25.500f, 38.000f}, //  4 U10 @ U2
  {7.500f, 38.000f}, //  5 U9 @ U1
  {25.500f, 56.000f}, //  6 U14 @ U6
  {7.500f, 56.000f}, //  7 U13 @ U5
  {11.250f, 92.500f}, //  8 U17 @ SW1
  {22.750f, 92.500f}, //  9 U18 @ SW2
  {34.250f, 92.500f}, // 10 U19 @ SW3
  {45.750f, 92.500f}, // 11 U20 @ SW4
  {57.250f, 92.500f}, // 12 U21 @ SW5
  {68.750f, 92.500f}, // 13 U22 @ SW6
  {74.500f, 103.500f}, // 14 U29 @ SW13
  {63.000f, 103.500f}, // 15 U28 @ SW12
  {51.500f, 103.500f}, // 16 U27 @ SW11
  {40.000f, 103.500f}, // 17 U26 @ SW10
  {28.500f, 103.500f}, // 18 U25 @ SW9
  {17.000f, 103.500f}, // 19 U24 @ SW8
  {5.500f, 103.500f}, // 20 U23 @ SW7
};

static const PanelPoint panel_encoder_pos[8] =
{
  {72.500f, 38.000f}, // 0 U4 ch5
  {54.500f, 38.000f}, // 1 U3 ch4
  {25.500f, 38.000f}, // 2 U2 ch1
  {7.500f, 38.000f}, // 3 U1 ch0
  {7.500f, 56.000f}, // 4 U5 ch2
  {25.500f, 56.000f}, // 5 U6 ch3
  {72.500f, 56.000f}, // 6 U7 ch7
  {54.500f, 56.000f}, // 7 U8 ch6
};

static const PanelPoint panel_output_pos[8] =
{
  {7.500f, 5.000f}, // ch0 J1 dac7
  {20.500f, 5.000f}, // ch1 J2 dac3
  {7.500f, 15.000f}, // ch2 J3 dac5
  {20.500f, 15.000f}, // ch3 J4 dac1
  {59.500f, 5.000f}, // ch4 J5 dac6
  {72.500f, 5.000f}, // ch5 J6 dac2
  {59.500f, 15.000f}, // ch6 J7 dac4
  {72.500f, 15.000f}, // ch7 J8 dac0
};

static const PanelPoint panel_input_pos[4] =
{
  {33.500f, 8.000f}, // in0 J9 adc2
  {46.500f, 8.000f}, // in1 J10 adc3
  {33.500f, 18.000f}, // in2 J11 adc0
  {46.500f, 18.000f}, // in3 J12 adc1
};

static const PanelPoint panel_slider_pos = {40.000f, 80.000f};
#define PANEL_SLIDER_TRAVEL_MM 49.0f

#endif /* BMCV_PANEL_LAYOUT_H_ */
