// Generated by tools/gen_panel_spec.py - do not edit.
// Panel geometry in mm, origin at the board's top-left corner.
// Regenerate with `just panel`.
#ifndef BMCV_PANEL_LAYOUT_H_
#define BMCV_PANEL_LAYOUT_H_

#include <stdint.h>

typedef struct { float x, y; } PanelPoint;

#define PANEL_BOARD_W_MM 80.0f
#define PANEL_BOARD_H_MM 108.0f
#define PANEL_HP 16

// The VCV Rack panel: a whole number of HP wide, so the module lands on
// the rail grid. Add the offset to any position above to get panel space.
#define PANEL_VCV_W_MM 81.28f
#define PANEL_VCV_H_MM 128.5f
#define PANEL_VCV_OFF_X_MM 0.64f
#define PANEL_VCV_OFF_Y_MM 10.25f

// The exported panel artwork covers the whole panel it was drawn for, not
// just the board, so laying it over a panel of a different width means
// placing it by its own board origin rather than by its corner.
#define PANEL_ART_W_MM 81.0f
#define PANEL_ART_H_MM 128.5f
#define PANEL_ART_OFF_X_MM 0.5f
#define PANEL_ART_OFF_Y_MM 10.25f

static const PanelPoint panel_button_pos[24] =
{
  {25.500f, 56.000f}, //  0 U6
  {7.500f, 38.000f}, //  1 U1
  {25.500f, 38.000f}, //  2 U2
  {54.500f, 38.000f}, //  3 U3
  {7.500f, 56.000f}, //  4 U5
  {72.500f, 38.000f}, //  5 U4
  {72.500f, 56.000f}, //  6 U7
  {54.500f, 56.000f}, //  7 U8
  {22.750f, 92.500f}, //  8 SW2
  {17.000f, 103.500f}, //  9 SW8
  {11.250f, 92.500f}, // 10 SW1
  {5.500f, 103.500f}, // 11 SW7
  {34.250f, 92.500f}, // 12 SW3
  {28.500f, 103.500f}, // 13 SW9
  {40.000f, 103.500f}, // 14 SW10
  {45.750f, 92.500f}, // 15 SW4
  {57.250f, 92.500f}, // 16 SW5
  {68.750f, 92.500f}, // 17 SW6
  {51.500f, 103.500f}, // 18 SW11
  {63.000f, 103.500f}, // 19 SW12
  {74.500f, 103.500f}, // 20 SW13
  {40.000f, 38.000f}, // 21 SW14
  {40.000f, 52.000f}, // 22 SW15
  {40.000f, 66.000f}, // 23 SW16
};

static const PanelPoint panel_led_pos[21] =
{
  {54.500f, 56.000f}, //  0 U16 @ U8
  {72.500f, 56.000f}, //  1 U15 @ U7
  {72.500f, 38.000f}, //  2 U12 @ U4
  {54.500f, 38.000f}, //  3 U11 @ U3
  {25.500f, 38.000f}, //  4 U10 @ U2
  {7.500f, 38.000f}, //  5 U9 @ U1
  {25.500f, 56.000f}, //  6 U14 @ U6
  {7.500f, 56.000f}, //  7 U13 @ U5
  {11.250f, 92.500f}, //  8 U17 @ SW1
  {22.750f, 92.500f}, //  9 U18 @ SW2
  {34.250f, 92.500f}, // 10 U19 @ SW3
  {45.750f, 92.500f}, // 11 U20 @ SW4
  {57.250f, 92.500f}, // 12 U21 @ SW5
  {68.750f, 92.500f}, // 13 U22 @ SW6
  {74.500f, 103.500f}, // 14 U29 @ SW13
  {63.000f, 103.500f}, // 15 U28 @ SW12
  {51.500f, 103.500f}, // 16 U27 @ SW11
  {40.000f, 103.500f}, // 17 U26 @ SW10
  {28.500f, 103.500f}, // 18 U25 @ SW9
  {17.000f, 103.500f}, // 19 U24 @ SW8
  {5.500f, 103.500f}, // 20 U23 @ SW7
};

static const PanelPoint panel_encoder_pos[8] =
{
  {72.500f, 38.000f}, // 0 U4 ch5
  {54.500f, 38.000f}, // 1 U3 ch4
  {25.500f, 38.000f}, // 2 U2 ch1
  {7.500f, 38.000f}, // 3 U1 ch0
  {7.500f, 56.000f}, // 4 U5 ch2
  {25.500f, 56.000f}, // 5 U6 ch3
  {72.500f, 56.000f}, // 6 U7 ch7
  {54.500f, 56.000f}, // 7 U8 ch6
};

static const PanelPoint panel_output_pos[8] =
{
  {7.500f, 5.000f}, // ch0 J1 dac7
  {20.500f, 5.000f}, // ch1 J2 dac3
  {7.500f, 15.000f}, // ch2 J3 dac5
  {20.500f, 15.000f}, // ch3 J4 dac1
  {59.500f, 5.000f}, // ch4 J5 dac6
  {72.500f, 5.000f}, // ch5 J6 dac2
  {59.500f, 15.000f}, // ch6 J7 dac4
  {72.500f, 15.000f}, // ch7 J8 dac0
};

static const PanelPoint panel_input_pos[4] =
{
  {33.500f, 8.000f}, // in0 J9 adc2
  {46.500f, 8.000f}, // in1 J10 adc3
  {33.500f, 18.000f}, // in2 J11 adc0
  {46.500f, 18.000f}, // in3 J12 adc1
};

static const PanelPoint panel_slider_pos = {40.000f, 80.000f};
#define PANEL_SLIDER_TRAVEL_MM 49.0f

// What each button does, for a host's tooltips. Same text the web
// frontend puts in its hover hint, from the same roles.
static const char* const panel_button_label[24] =
{
  "U6 - ch3 push", //  0
  "U1 - ch0 push", //  1
  "U2 - ch1 push", //  2
  "U3 - ch4 push", //  3
  "U5 - ch2 push", //  4
  "U4 - ch5 push", //  5
  "U7 - ch7 push", //  6
  "U8 - ch6 push", //  7
  "SW2 - SHP / SYS / D#", //  8
  "SW8 - scene 1 / D", //  9
  "SW1 - FRQ / STA / C#", // 10
  "SW7 - scene 0 / C", // 11
  "SW3 - MOD / QNT", // 12
  "SW9 - scene 2 / E", // 13
  "SW10 - scene 3 / F", // 14
  "SW4 - PHS / MON / F#", // 15
  "SW5 - AMP / SAV / G#", // 16
  "SW6 - OFS / STB / A#", // 17
  "SW11 - scene 4 / G", // 18
  "SW12 - scene 5 / A", // 19
  "SW13 - scene 6 / B", // 20
  "SW14 - CLR", // 21
  "SW15 - CPY", // 22
  "SW16 - MUT", // 23
};

// The legends printed beside a switch: the parameter it selects above it,
// the shift mode it latches below. A host that lights the cap draws these
// itself rather than taking them from its panel image, so that they follow
// hw_setup.c if a button is ever reassigned. Empty where there is no such
// role - scene buttons carry neither.
static const char* const panel_button_param[24] =
{
  "", //  0 U6
  "", //  1 U1
  "", //  2 U2
  "", //  3 U3
  "", //  4 U5
  "", //  5 U4
  "", //  6 U7
  "", //  7 U8
  "SHP", //  8 SW2
  "", //  9 SW8
  "FRQ", // 10 SW1
  "", // 11 SW7
  "MOD", // 12 SW3
  "", // 13 SW9
  "", // 14 SW10
  "PHS", // 15 SW4
  "AMP", // 16 SW5
  "OFS", // 17 SW6
  "", // 18 SW11
  "", // 19 SW12
  "", // 20 SW13
  "", // 21 SW14
  "", // 22 SW15
  "", // 23 SW16
};

static const char* const panel_button_mode[24] =
{
  "", //  0 U6
  "", //  1 U1
  "", //  2 U2
  "", //  3 U3
  "", //  4 U5
  "", //  5 U4
  "", //  6 U7
  "", //  7 U8
  "SYS", //  8 SW2
  "", //  9 SW8
  "STA", // 10 SW1
  "", // 11 SW7
  "QNT", // 12 SW3
  "", // 13 SW9
  "", // 14 SW10
  "MON", // 15 SW4
  "SAV", // 16 SW5
  "STB", // 17 SW6
  "", // 18 SW11
  "", // 19 SW12
  "", // 20 SW13
  "CLR", // 21 SW14
  "CPY", // 22 SW15
  "MUT", // 23 SW16
};

// What sits behind each button, so a host does not have to walk the
// HwSetup index tables to find out. -1 where there is no LED.
typedef enum { PANEL_BTN_ENCODER_PUSH, PANEL_BTN_RGB_SWITCH, PANEL_BTN_TACTILE } PanelButtonKind;

static const PanelButtonKind panel_button_kind[24] =
{
  PANEL_BTN_ENCODER_PUSH, //  0 U6
  PANEL_BTN_ENCODER_PUSH, //  1 U1
  PANEL_BTN_ENCODER_PUSH, //  2 U2
  PANEL_BTN_ENCODER_PUSH, //  3 U3
  PANEL_BTN_ENCODER_PUSH, //  4 U5
  PANEL_BTN_ENCODER_PUSH, //  5 U4
  PANEL_BTN_ENCODER_PUSH, //  6 U7
  PANEL_BTN_ENCODER_PUSH, //  7 U8
  PANEL_BTN_RGB_SWITCH, //  8 SW2
  PANEL_BTN_RGB_SWITCH, //  9 SW8
  PANEL_BTN_RGB_SWITCH, // 10 SW1
  PANEL_BTN_RGB_SWITCH, // 11 SW7
  PANEL_BTN_RGB_SWITCH, // 12 SW3
  PANEL_BTN_RGB_SWITCH, // 13 SW9
  PANEL_BTN_RGB_SWITCH, // 14 SW10
  PANEL_BTN_RGB_SWITCH, // 15 SW4
  PANEL_BTN_RGB_SWITCH, // 16 SW5
  PANEL_BTN_RGB_SWITCH, // 17 SW6
  PANEL_BTN_RGB_SWITCH, // 18 SW11
  PANEL_BTN_RGB_SWITCH, // 19 SW12
  PANEL_BTN_RGB_SWITCH, // 20 SW13
  PANEL_BTN_TACTILE, // 21 SW14
  PANEL_BTN_TACTILE, // 22 SW15
  PANEL_BTN_TACTILE, // 23 SW16
};

static const int8_t panel_button_led[24] =
{
  6, //  0 U6
  5, //  1 U1
  4, //  2 U2
  3, //  3 U3
  7, //  4 U5
  2, //  5 U4
  1, //  6 U7
  0, //  7 U8
  9, //  8 SW2
  19, //  9 SW8
  8, // 10 SW1
  20, // 11 SW7
  10, // 12 SW3
  18, // 13 SW9
  17, // 14 SW10
  11, // 15 SW4
  12, // 16 SW5
  13, // 17 SW6
  16, // 18 SW11
  15, // 19 SW12
  14, // 20 SW13
  -1, // 21 SW14
  -1, // 22 SW15
  -1, // 23 SW16
};

// Each encoder's other two halves: the button under the same finger and
// the WS2811 behind it, plus the channel it drives.
typedef struct { int8_t push_button, led, channel; } PanelEncoder;

static const PanelEncoder panel_encoder[8] =
{
  {5, 2, 5}, // 0 U4
  {3, 3, 4}, // 1 U3
  {2, 4, 1}, // 2 U2
  {1, 5, 0}, // 3 U1
  {4, 7, 2}, // 4 U5
  {0, 6, 3}, // 5 U6
  {6, 1, 7}, // 6 U7
  {7, 0, 6}, // 7 U8
};

// The four M3 slots, in artwork space like PANEL_ART_* above - they are
// outside the board, so board coordinates cannot express them.
static const PanelPoint panel_mount_pos[4] =
{
  {7.450f, 2.960f},
  {73.470f, 2.960f},
  {7.450f, 125.450f},
  {73.470f, 125.450f},
};

#endif /* BMCV_PANEL_LAYOUT_H_ */
